### ISSUE TITLE
No orcid for Steven B. Charnley ?

### ISSUE THREAD

**Issue by eteq** [migueldvb/cine#1]
While reviewing the JOSS paper for openjournals/joss-reviews#182, I notice there's an author with no orcid (Steven B. Charnley).  Is this intended (i.e., he has no orcid), or an oversight?

**Comment by eteq** [comment]
(This is part of the review in openjournals/joss-reviews#182)

**Comment by migueldvb** [comment]
I think he plans to register with orcid soon. Now the markdown file compiles using the command `pandoc -S -o paper.pdf -V geometry:margin=1in --filter pandoc-citeproc paper.md --template /path/to/latex.template` without the orcid identifier but will be happy to add the number later.

**Comment by eteq** [comment]
Will leave it open for whenever he does register, but I presume not critical for JOSS acceptance

**Comment by migueldvb** [comment]
Closing this as it will not be fixed before acceptance.
