### ISSUE TITLE
Setuptools should be a requirement/bootstrapped

### ISSUE THREAD

**Issue by eteq** [migueldvb/cine#2]
If I try to do a ``python setup.py build`` on a minimal python setup, I get ``ImportError: No module named setuptools``.  There are two solutions I know of:

1. use https://bootstrap.pypa.io/ez_setup.py as a bootstrap script which auto-installs setuptools. 
2. add "pip install setuptools" to the setup instructions (and maybe catch the import error in your setup.py)

I'd say just do 1, except that its notes say that approach is deprecated.  So either of these work.

**Comment by migueldvb** [comment]
That is a good point. I have added a fallback import of setup from distutils. The `setup.py` script should work now with both setuptools and distutils.

**Comment by eteq** [comment]
(This is part of the review in openjournals/joss-reviews#182)

**Comment by eteq** [comment]
Great, thanks for the real-time peer review, @migueldvb ! ;)
