### ISSUE TITLE
Python 2 not supported?

### ISSUE THREAD

**Issue by eteq** [migueldvb/cine#4]
If I try to import `cine` from python 2.7, I get a ``SyntaxError: only named arguments may follow *expression``... But the ``setup.py`` implies that 2.x is supposed to be supported.

I'm agnostic whether you want to support py2 or not, but it should be stated in the readme (and the ``setup.py`` should be consistent what major version(s) of python are supported.

**Comment by eteq** [comment]
(This is part of the review in openjournals/joss-reviews#182)

**Comment by migueldvb** [comment]
Thanks for catching this issue. It looks like this is the only thing that prevents the code from working in python 2.7 so I will fix this and keep support for 2.7 in setup.py.

There is now travis continuous integration set up in the repository to build and test the software after every commit in python 2.7, 3.4, 3.5 and 3.6 that should find these problems. I have also added the badge that shows the status of the build in the README file.
